/**
 * This file belongs to the BPELUnit utility and Eclipse plugin set. See enclosed
 * license file for more information.
 * 
 */
package net.bpelunit.toolsupport.editors.src;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.ui.editors.text.TextEditor;

/**
 * An XMLEditor to be used in the BPELUnit Editors source page. This class and other classes in this
 * package have been pre-generated by the "New Plugin" wizard of Eclipse 3.2
 * 
 * @version $Id$
 * @author Philip Mayer
 * 
 */
public class XMLEditor extends TextEditor {

	private ColorManager colorManager;

	public XMLEditor() {
		super();
		colorManager= new ColorManager();
		setSourceViewerConfiguration(new XMLConfiguration(colorManager));
		setDocumentProvider(new XMLDocumentProvider());
	}

	@Override
	public void doSave(IProgressMonitor progressMonitor) {
		super.doSave(progressMonitor);
	}

	@Override
	public void dispose() {
		colorManager.dispose();
		super.dispose();
	}

}
