#!/bin/bash

# BPEL statistics tool launch script
# (C) 2013 Antonio García Domínguez

# Alternative implementation of the "-f" option for readlink(1), since
# the Mac (BSD) version does not have it. It's not a perfect replacement
# but it should work for our case. It's been taken from:
#
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
#
readlink_f() {
    TARGET_FILE=$1

    cd $(dirname "$TARGET_FILE")
    TARGET_FILE=$(basename "$TARGET_FILE")

    # Iterate down a (possible) chain of symlinks
    while [ -L "$TARGET_FILE" ]
    do
        TARGET_FILE=$(readlink "$TARGET_FILE")
        cd $(dirname "$TARGET_FILE")
        TARGET_FILE=$(basename "$TARGET_FILE")
    done

    # Compute the canonicalized name by finding the physical path
    # for the directory we're in and appending the target file.
    PHYS_DIR=`pwd -P`
    RESULT=$PHYS_DIR/$TARGET_FILE
    echo $RESULT
}

# By default, the .jar and the script are distributed together
JARFILE=$(dirname $(readlink -f "$0"))/${project.artifactId}.jar

if [ -z "$JAVA_HOME" ]; then
  echo "Please set the JAVA_HOME environment variable to the path to your JVM"
  exit 1
fi

$JAVA_HOME/bin/java -Xmx512m -Xss20m -jar "$JARFILE" $@
